#!/bin/bash
#declaraciones
export GRUPO01=`pwd`
export CONFDIR="$GRUPO01/conf"

clear

#funciona verificacion
function Pregunta_SiNo {
	echo  $1
	local Acepta="null"
	while [ "$Acepta" != "si" -a "$Acepta" != "no" ]
	do
		read Acepta
		Acepta=`echo "$Acepta" | tr '[:upper:]' '[:lower:]'`
		if [ "$Acepta" == "s" ];then Acepta="si";fi
		if [ "$Acepta" == "n" ];then Acepta="no";fi
		if [ "$Acepta" != "si" -a "$Acepta" != "no" ]; then
			echo "No se ingreso una opcion valida. Acepta? Si - No"
		fi
	done
	if [ "$Acepta" == "no" ]; then
		return 0
	fi	
	return 1
}

function Verificar_perl {
	Perl=`perl --version`
	Version=`echo $Perl | sed -n 's/.*v\([0-9]\)\.[0-9][0-9]\.[0-9].*/\1/p'`
	if [[ $Version -lt 5 ]]; then
		echo "TP SO7508 Primer Cuatrimestre 2014. Tema C Copyright © Grupo 01
Para instalar el TP es necesario contar con Perl 5 o superior. Efectue su instalacion e intentelo nuevamente.
Proceso de Instalacion Cancelado"

		./datos/bin/Logging Installer "TP SO7508 Primer Cuatrimestre 2014. Tema C Copyright © Grupo 01
Para instalar el TP es necesario contar con Perl 5 o superior. Efectue su instalacion e intentelo nuevamente.
Proceso de Instalacion Cancelado" ERROR

		exit 1
	fi
	echo "TP SO7508 Primer Cuatrimestre 2014. Tema C Copyright © Grupo 01
Perl Version: $Perl"
 	./datos/bin/Logging Installer "TP SO7508 Primer Cuatrimestre 2014. Tema C Copyright © Grupo 01
Perl Version: $Perl" INFO
}

function Verificar_tamano {
	valorIngresado="$1"
	valorPorDefecto="$2"
	estado=`echo $valorIngresado | sed -n "s/\(.*[^0-9].*\)/ERROR/p"`
	if [ "$estado" == "ERROR" -o "$1" == "" ]
	then 
		resultado=$valorPorDefecto
	else
		resultado=$1
	fi
	echo $resultado
}

function Verificar_tamano_disco {
	lineaDiscoDisponible=`df --block-size M /home` 
	lineaDiscoDisponible=`echo "$lineaDiscoDisponible" | grep -v "Filesystem"`

	# obtengo tamano disponible del disco 
	espacioDisponible=`echo $lineaDiscoDisponible | cut -f 4 -d ' '`  
	
	# obtengo unicamente el numero del espacio disponible en disco. saco unidades
	espacioDisponible=`echo $espacioDisponible | sed -n 's-^\(.*\)M$-\1-p'`

	echo $espacioDisponible
}

#Recibe 4 parametros [variable a guardar el resultado,salida en pantalla y log, log fracaso,pathdefecto]
function Obtener_path {
	#devolucion de parametros basada en http://www.linuxjournal.com/content/return-values-bash-functions
	local  Resultado=$1
	local  Resultadoparcial
	read Resultadoparcial
	if [ "$Resultadoparcial" == "" ]
    	then
		Resultadoparcial=$3	
		echo "Error: El valor ingresado es inválido, se tomará el predeterminado: $3"
    	else
		Resultadoparcial=$Resultadoparcial
	fi
	
	Resultadoparcial=`echo "$Resultadoparcial" | grep '^[^=]*$'`
	if [ "$Resultadoparcial" == "" ]
	then
		echo "Error: El valor ingresado para $1 es inválido, se tomará el predeterminado: $3"
		Resultadoparcial=$3	
	fi
	
	./datos/bin/Logging Installer "$2 $Resultadoparcial" INFO
    	eval $Resultado="'$Resultadoparcial'"
}

#Recibe 3 parametros [variable a guardar el resultado,salida en pantalla y log,pathdefecto]
function Obtener_valor {
	#devolucion de parametros basada en http://www.linuxjournal.com/content/return-values-bash-functions
	local  Resultado=$1
	local  Resultadoparcial
	read Resultadoparcial
	if [ "$Resultadoparcial" == "" ] 
	then
		Resultadoparcial=$3
		echo "El valor ingresado para $1 es inválido, se tomará el predeterminado: $3"
	fi

	Resultadoparcial=`echo "$Resultadoparcial" | grep '^[^=]*$'`
	if [ "$Resultadoparcial" == "" ]
	then
		echo "El valor ingresado para $1 es inválido, se tomará el predeterminado: $3"
		./datos/bin/Logging Installer "Error: El valor ingresado para $1 es inválido, se tomará el predeterminado." ERR
		Resultadoparcial=$3	
	fi

	./datos/bin/Logging Installer "$2 $Resultadoparcial" INFO
	eval $Resultado="'$Resultadoparcial'"
}

#Recibe 5 parametros [variable a guardar el resultado,salida en pantalla y log, log error, pathdefecto, cota]
function Obtener_numero {
	#devolucion de parametros basada en http://www.linuxjournal.com/content/return-values-bash-functions
	local  Resultado=$1
	local  Resultadoparcial
	read Resultadoparcial
	if [ "$Resultadoparcial" == "" ]
	then
		Resultadoparcial="ERROR"
	fi
	Resultadoparcial=`echo "$Resultadoparcial" | sed 's/^.*[^0-9].*$/ERROR/'`
	if [ "$Resultadoparcial" == "ERROR" ] 
	then
		echo "Error: El número ingresado para $1 es inválido, se tomará el predeterminado: $4"
		./datos/bin/Logging Installer "Error: El número ingresado para $1 es inválido, se tomará el predeterminado." ERR
		Resultadoparcial=$4
		eval $Resultado="'$Resultadoparcial'"
		return 0
	fi

	if [ $Resultadoparcial -lt $5 ]
	then
		Resultadoparcial=$4
	fi
	./datos/bin/Logging Installer "$2 $Resultadoparcial" INFO
	eval $Resultado="'$Resultadoparcial'"
}

#recibe: $1: mensaje a mostrar
#$2: directorio del cual se quiere mostrar el path y archivos contenidos dentro de ese path
#3:booleano indicando si se quiere listar los archivos o no (1=si 0=no)	
function Path_y_Archivos {
	if [ "$3" -eq 1 ]
	then	
		if [ -d "$2" ]
		then
			archivos=`ls -1 "$2"`	
		else 
			archivos=" "
		fi
	else
		archivos=" "
	fi	
	if [ "$archivos" != " " ]
	then
		resultado="$1 $2 
Archivos en $2:
$archivos "
	else
		resultado="$1 $2"
	fi
	echo "$resultado"
	./datos/bin/Logging Installer "$resultado" INFO
}
#Creo directorios

# 1er parametro directorio a crear, 2do parametro directorio padre
function Crear_directorios {
	mkdir -p "$1"
}

function Creacion_de_directorios {
	if [ $1 != 1 ]; then echo "Creando estructuras de directorio . . . .";fi
#	Crear_directorios "$BINDIR" "$GRUPO01"
#	Crear_directorios "$MAEDIR" "$GRUPO01"
#	Crear_directorios "$MAEDIR/precios" "$GRUPO01"
#	Crear_directorios "$MAEDIR/precios/proc" "$GRUPO01"
#	Crear_directorios "$NOVEDIR" "$GRUPO01"
#	Crear_directorios "$ACEPDIR" "$GRUPO01"
#	Crear_directorios "$ACEPDIR/proc" "$GRUPO01"
#	Crear_directorios "$INFODIR" "$GRUPO01"
#	Crear_directorios "$INFODIR/pres" "$GRUPO01"
#	Crear_directorios "$RECHDIR" "$GRUPO01"
#	Crear_directorios "$LOGDIR" "$GRUPO01"
	
	dir_actual=`pwd`
	
	Crear_directorios "$BINDIR"
	cd "$BINDIR"
	BINDIR=`pwd`
	cd "$dir_actual"

	Crear_directorios "$MAEDIR"
	Crear_directorios "$MAEDIR/precios"
	Crear_directorios "$MAEDIR/precios/proc"
	cd "$MAEDIR"
	MAEDIR=`pwd`
	cd "$dir_actual"
	
	
	Crear_directorios "$NOVEDIR"
	cd "$NOVEDIR"
	NOVEDIR=`pwd`
	cd "$dir_actual"

	Crear_directorios "$ACEPDIR"
	Crear_directorios "$ACEPDIR/proc"
	cd "$ACEPDIR"
	ACEPDIR=`pwd`
	cd "$dir_actual"

	Crear_directorios "$INFODIR"
	Crear_directorios "$INFODIR/pres"
	cd "$ACEPDIR"
	ACEPDIR=`pwd`
	cd "$dir_actual"
	
	Crear_directorios "$RECHDIR"
	cd "$RECHDIR"
	RECHDIR=`pwd`
	cd "$dir_actual"
	
	Crear_directorios "$LOGDIR"
	cd "$LOGDIR"
	LOGDIR=`pwd`
	cd "$dir_actual"
}

#$1=subdirectorio $2=expresion que matchea, $3 dir destino
function Copiar_archivos {
	declare local directorioActual=`pwd`
	cd "$1"
	ListaArchivos=`ls $1/$2`
	for Archivo in $ListaArchivos;
	do
		echo "archivo $Archivo"
		local Nombre_archivo=`echo $Archivo | sed -n 's/.*[/]\([^/]*\)/\1/p'`
		if [[ ! -f "$3"/$Nombre_archivo ]]; then
			cp -a "$Archivo" "$3/$Nombre_archivo"
		fi
	done
	cd "$directorioActual"
}

#instalo archivos
function Instalacion_archivos {
	echo "Instalando Archivos Maestros y tablas"
	Copiar_archivos "$GRUPO01/datos" "*.mae" "$MAEDIR"
	Copiar_archivos "$GRUPO01/datos" "*.tab" "$MAEDIR"
	echo
	echo "Instalando Programas y Funciones"
#	Copiar_archivos "$GRUPO01/datos" "*.sh" "$GRUPO01"/"$BINDIR"
#	Copiar_archivos "$GRUPO01/datos" "*.pl" "$GRUPO01"/"$BINDIR"	

	Copiar_archivos "$GRUPO01/datos/bin" "Start" "$BINDIR"
	Copiar_archivos "$GRUPO01/datos/bin" "Stop" "$BINDIR"
	Copiar_archivos "$GRUPO01/datos/bin" "Mover" "$BINDIR"
	Copiar_archivos "$GRUPO01/datos/bin" "Rating" "$BINDIR"
	Copiar_archivos "$GRUPO01/datos/bin" "Reporting" "$BINDIR"
	Copiar_archivos "$GRUPO01/datos/bin" "Logging" "$BINDIR"
	Copiar_archivos "$GRUPO01/datos/bin" "Listener" "$BINDIR"
	Copiar_archivos "$GRUPO01/datos/bin" "Masterlist" "$BINDIR"
	Copiar_archivos "$GRUPO01/datos/bin" "Initializer" "$BINDIR"
}
#Actualizo archivos de configuracion
function Actualizacion_archivos_configuracion {
	if [ -f "$CONFDIR/Installer.conf" ] 
	then
		rm $CONFDIR/Installer.conf
	fi
	date=`date`

echo "GRUPO01=$GRUPO01=$USER=$date
CONFDIR=$CONFDIR=$USER=$date
BINDIR=$BINDIR=$USER=$date 
MAEDIR=$MAEDIR=$USER=$date
NOVEDIR=$NOVEDIR=$USER=$date
DATASIZE=$DATASIZE=$USER=$date 
ACEPDIR=$ACEPDIR=$USER=$date
INFODIR=$INFODIR=$USER=$date
RECHDIR=$RECHDIR=$USER=$date
LOGDIR=$LOGDIR=$USER=$date
LOGEXT=$LOGEXT=$USER=$date
LOGSIZE=$LOGSIZE=$USER=$date" >> "$CONFDIR/Installer.conf"

}

# Rescata el valor que corresponde a la variable pasada por parametro  
# que se encuentra en el archivo de configuracion
# $1:Variable
function Tomar_Variable { 
	declare local var=`grep '^'$1'=[^=]*=[^=]*=[^=]*$' "$CONFDIR/Installer.conf" | sed 's@^[^=]*=\([^=]*\)=.*@\1@'`
	
	if [  "$1" == DATASIZE  -o  "$1" == LOGSIZE  ] 
	then
		var=`echo "$var" | sed 's@[0-9]*[^0-9]\+.*@@'`
	fi
	
	if [ "$var" == "" ] 
	then
		echo "Error: registro $1 inexistente o mal formado en el archivo de configuración."
		./datos/bin/Logging Installer "Error: registro $1 inexistente o mal formado en el archivo de configuración." ERR
		echo "Por favor, vuelva a instalar el sistema siguiendo el README desde el comienzo."
		exit 1
	fi
	eval "$1=\"$var\""
	return 0
}


function Verificar_archivos_faltantes {
	ERROR=0
	conf_roto=0
	
	#verifico cada archivo que esta en BINDIR
	Tomar_Variable BINDIR
	Tomar_Variable NOVEDIR
	Tomar_Variable DATASIZE
	Tomar_Variable ACEPDIR
	Tomar_Variable RECHDIR
	Tomar_Variable INFODIR
	Tomar_Variable LOGDIR
	Tomar_Variable LOGEXT
	Tomar_Variable LOGSIZE
	Tomar_Variable MAEDIR

	#verifico cada archivo de tipo .mae y .tab que se encuentran en MAEDIR
	if [ ! -f "$MAEDIR/asociados.mae" ] 
	then
		Faltantes="$Faltantes 
		asociados.mae"
		if [ ! -f  "$GRUPO01/datos/asociados.mae" ]
		 then
			ERROR=1
		fi
	fi
	if [ ! -f "$MAEDIR/super.mae" ] 
	then
		Faltantes="$Faltantes 
		super.mae"
		if [ ! -f  "$GRUPO01/datos/super.mae" ]
		 then
			ERROR=1
		fi
	fi
	if [ ! -f "$MAEDIR/um.tab" ] 
	then
		Faltantes="$Faltantes 
		um.tab"
		if [ ! -f  "$GRUPO01/datos/um.tab" ]
		 then
			ERROR=1
		fi
	fi
	
	#verifico archivos en BINDIR
	if [ ! -f "$BINDIR/Initializer" ] 
	then
		Faltantes="$Faltantes 
		Initializer"
		if [ ! -f  "$GRUPO01/datos/bin/Initializer" ]
		 then
			ERROR=1
		fi
	fi
	if [ ! -f "$BINDIR/Listener" ] 
	then
		Faltantes="$Faltantes 
		Listener"
		if [ ! -f  "$GRUPO01/datos/bin/Listener" ]
		 then
			ERROR=1
		fi
	fi
	if [ ! -f "$BINDIR/Masterlist" ] 
	then
		Faltantes="$Faltantes 
		Masterlist"
		if [ ! -f  "$GRUPO01/datos/bin/Masterlist" ]
		 then
			ERROR=1
		fi
	fi
	if [ ! -f "$BINDIR/Logging" ] 
	then
		Faltantes="$Faltantes 
		Logging"
		if [ ! -f  "$GRUPO01/datos/bin/Logging" ]
		 then
			ERROR=1
		fi
	fi
	if [ ! -f "$BINDIR/Mover" ] 
	then
		Faltantes="$Faltantes 
		Mover"
		if [ ! -f  "$GRUPO01/datos/bin/Mover" ]
		 then
			ERROR=1
		fi
	fi
	if [ ! -f "$BINDIR/Rating" ] 
	then
		Faltantes="$Faltantes 
		Rating"
		if [ ! -f  "$GRUPO01/datos/bin/Rating" ]
		 then
			ERROR=1
		fi
	fi
	if [ ! -f "$BINDIR/Start" ] 
	then
		Faltantes="$Faltantes 
		Start"
		if [ ! -f  "$GRUPO01/datos/bin/Start" ]
		 then
			ERROR=1
		fi
	fi
	if [ ! -f "$BINDIR/Stop" ] 
	then
		Faltantes="$Faltantes 
		Stop"
		if [ ! -f  "$GRUPO01/datos/bin/Stop" ]
		 then
			ERROR=1
		fi
	fi
	if [ ! -f "$BINDIR/Reporting" ] 
	then
		Faltantes="$Faltantes 
		Reporting"
		if [ ! -f  "$GRUPO01/datos/bin/Reporting" ]
		 then
			ERROR=1
		fi
	fi


	#LISTO DIRECTORIOS.
	echo
	echo "TP SO7508 Primer Cuatrimestre 2014. Tema C Copyright © Grupo 01"
	./datos/bin/Logging Installer "TP SO7508 Primer Cuatrimestre 2014. Tema C Copyright © Grupo 01" INFO
	echo "Direct. de Configuracion: $BINDIR/ Archivos:"
	./datos/bin/Logging Installer "Direct. de Configuracion: /$BINDIR/ Archivos:" INFO
	if [ -d "$BINDIR" ] 
	then
		ls "$BINDIR"
		Archivosbin=`ls "$BINDIR" `
		./datos/bin/Logging Installer "$Archivosbin" INFO
	else
		echo "Directorio $BINDIR inexistente" 
		./datos/bin/Logging Installer "Directorio $BINDIR inexistente" ERR
		conf_roto=1
	fi
	echo
	echo "Direct Maestros y Tablas: $MAEDIR/ Archivos:"
	./datos/bin/Logging Installer "Direct Maestros y Tablas: /$MAEDIR/ Archivos:" INFO
	if [ -d "$MAEDIR" ]
	then
		ls "$MAEDIR"
		Archivosmae=`ls "$MAEDIR" `
		./datos/bin/Logging Installer "$Archivosmae" INFO
	else
		echo "Directorio $MAEDIR inexistente"
		./datos/bin/Logging Installer "Directorio $MAEDIR inexistente" ERR
		conf_roto=1
	fi
	echo
	echo "Direct. de Configuracion: $CONFDIR/ Archivos:"
	./datos/bin/Logging Installer "Direct. de Configuracion: /$CONFDIR/ Archivos:" INFO
	if [ -d "$CONFDIR" ] 
	then
		ls "$CONFDIR"
		Archivosconf=`ls "$CONFDIR" `
		./datos/bin/Logging Installer "$Archivosconf" INFO
	else
		echo "Directorio $CONFDIR inexistente"
		./datos/bin/Logging Installer "Directorio $CONFDIR inexistente" ERR
		conf_roto=1
	fi
	if [ ! -d "$NOVEDIR" ] 
	then
		echo "Directorio $NOVEDIR inexistente"
		./datos/bin/Logging Installer "Directorio $NOVEDIR inexistente" ERR
		conf_roto=1
	else 
		echo "Directorio de Novedades: $NOVEDIR"
		./datos/bin/Logging Installer "Directorio de Novedades: $NOVEDIR" INFO
	fi
	if [ ! -d "$ACEPDIR" ] 
	then
		echo "Directorio $ACEPDIR inexistente"
		./datos/bin/Logging Installer "Directorio $ACEPDIR inexistente" ERR
		conf_roto=1
	else
		echo "Novedades Aceptadas: $ACEPDIR"
		./datos/bin/Logging Installer "Novedades Aceptadas: $ACEPDIR" INFO
	fi
	if [ ! -d "$RECHDIR" ] 
	then
		echo "Directorio $RECHDIR inexistente"
		./datos/bin/Logging Installer "Directorio $RECHDIR inexistente" ERR
		conf_roto=1
	else
		echo "Novedades Rechazadas: $RECHDIR"
		./datos/bin/Logging Installer "Novedades Rechazadas: $RECHDIR" INFO
	fi
	if [ ! -d "$INFODIR" ] 
	then
		echo "Directorio $INFODIR inexistente"
		./datos/bin/Logging Installer "Directorio $INFODIR inexistente" ERR
		conf_roto=1
	else
		echo "Dir informes de salida: $INFODIR"
		./datos/bin/Logging Installer "Dir informes de salida: $INFODIR" INFO
	fi
	if [ ! -d "$LOGDIR" ] 
	then
		echo "Directorio $LOGDIR inexistente"
		./datos/bin/Logging Installer "Directorio $LOGDIR inexistente" ERR
		conf_roto=1
	else
		echo "Directorio de Logs de Comandos: $LOGDIR/<comando> $LOGEXT"
		./datos/bin/Logging Installer "Directorio de Logs de Comandos: $LOGDIR/<comando> $LOGEXT" INFO
	fi	

	if [ "$Faltantes" == "" -a $conf_roto -eq 0 ] 
	then
		echo "Estado de la instalacion: COMPLETA
Proceso de instalacion cancelado." 
		./datos/bin/Logging Installer "Estado de la instalacion: COMPLETA" INFO
		./datos/bin/Logging Installer "Proceso de instalacion cancelado." INFO
		exit 0;
	else 
		if [ $conf_roto -ne 0 ] 
		then
			echo "Se rompio el archivo de configuracion."
			./datos/bin/Logging Installer "Se rompio el archivo de configuracion." INFO
		fi
		echo "Estado de la instalacion: Incompleto"
		echo "Faltan Archivos: $Faltantes"
		./datos/bin/Logging Installer "Faltan Archivos: $Faltantes" INFO
		./datos/bin/Logging Installer "Estado de la instalacion: Incompleto" INFO
		Pregunta_SiNo "Desea completar la instalacion? (si-no)"
		if [ "$?" == 0 ] 
		then
			exit 0
		else 
			if [ $ERROR == 1 ] 
			then
				echo "No se encuentran los archivos fuentes, instalacion interrumpida."
				exit 1
			else
				Creacion_de_directorios 1
				tmp=`Copiar_archivos "$GRUPO01/datos" "*.mae" "$MAEDIR" `
				tmp=`Copiar_archivos "$GRUPO01/datos" "*.tab" "$MAEDIR" `
				tmp=`Copiar_archivos "$GRUPO01/datos/bin" "Start" "$BINDIR" `
				tmp=`Copiar_archivos "$GRUPO01/datos/bin" "Stop" "$BINDIR" `
				tmp=`Copiar_archivos "$GRUPO01/datos/bin" "Mover" "$BINDIR" `
				tmp=`Copiar_archivos "$GRUPO01/datos/bin" "Rating" "$BINDIR" `
				tmp=`Copiar_archivos "$GRUPO01/datos/bin" "Reporting" "$BINDIR"` 
				tmp=`Copiar_archivos "$GRUPO01/datos/bin" "Logging" "$BINDIR" `
				tmp=`Copiar_archivos "$GRUPO01/datos/bin" "Listener" "$BINDIR" `
				tmp=`Copiar_archivos "$GRUPO01/datos/bin" "Masterlist" "$BINDIR" `
				tmp=`Copiar_archivos "$GRUPO01/datos/bin" "Initializer" "$BINDIR" `
			fi
			
		fi
	fi
}

#pgm principal
clear
echo "Inicio de Ejecucion de Installer"
#verificacion de existencia de directorio
if [ ! -d "$CONFDIR" ] 
then 
	mkdir "$CONFDIR" 
fi
yaSeInstalo=1
if [ ! -f "$CONFDIR/Installer.conf" ]
then
	yaSeInstalo=0
fi	
if [ ! -f "$CONFDIR/Installer.log" ]
then
	#creo archivo de log
	touch "$CONFDIR/Installer.log"
fi	
chmod +x ./datos/bin/
echo "Log de la instalacion: $GRUPO01/$CONFDIR/Installer.log"
./datos/bin/Logging Installer "Log de la instalacion: $CONFDIR/Installer.log" INFO
echo "Directorio predefinido de Configuracion: $CONFDIR"
./datos/bin/Logging Installer "Directorio predefinido de Configuracion: $CONFDIR" INFO

if [ $yaSeInstalo -eq 1 ]
then	
	Verificar_archivos_faltantes

else

	echo 'TP SO7508 Primer Cuatrimestre 2014. Tema C Copyright © Grupo 01 Al instalar TP SO7508 Primer Cuatrimestre 2014 UD. expresa aceptar los terminos y condiciones del "ACUERDO DE LICENCIA DE SOFTWARE" incluido en este paquete.'
	Pregunta_SiNo "Acepta? Si – No'"
	if [ $? -eq 0 ]
	then
		exit 1
	else
		Verificar_perl
		instalar=0
		BINDIR="$GRUPO01/bin"
		MAEDIR="$GRUPO01/mae"
		NOVEDIR="$GRUPO01/arribos"
		DATASIZE=100
		ACEPDIR="$GRUPO01/aceptadas"
		INFODIR="$GRUPO01/informes"
		RECHDIR="$GRUPO01/rechazados"
		LOGDIR="$GRUPO01/log"
		LOGEXT="log"
		LOGSIZE=400

		while [ $instalar -eq 0 ]
		do
			echo
			# solicito valor de BINDIR
			echo "Defina el directorio de instalacion de los ejecutables ($BINDIR):"
			Obtener_path BINDIR "Directorio de instalacion de los ejecutables ($BINDIR):" "$BINDIR"
			echo
			# solicito valor de MAEDIR
			echo "Defina directorio para maestros y tablas ($MAEDIR):"
			Obtener_path MAEDIR "Directorio para maestros y tablas ($MAEDIR):" "$MAEDIR"
			echo 
			# solicito valor de NOVEDIR
			echo "Defina el Directorio de arribo de novedades ($NOVEDIR):"
			Obtener_path NOVEDIR "Directorio de arribo de novedades ($NOVEDIR):" "$NOVEDIR"
			echo
			# solicito valor de DATASIZE
			echo "Defina espacio minimo libre para el arribo de novedades en Mbytes ($DATASIZE):"
			Obtener_numero DATASIZE "Espacio minimo libre para el arribo de novedades en Mbytes ($DATASIZE):" "error" "$DATASIZE" 1
			DATASIZE=$(Verificar_tamano "$DATASIZE" $DATASIZE)
			#COMPRUEBO ESPACIO EN DISCO
			espacioDisponible=$(Verificar_tamano_disco)
			while [ $espacioDisponible -lt $DATASIZE ]
			do
				./datos/bin/Logging Installer "Insuficiente espacio en disco.
Espacio disponible: $espacioDisponible Mb.
Espacio requerido $DATASIZE Mb
Cancele la instalacion o intentelo nuevamente." ERR

				echo "Insuficiente espacio en disco." 
				echo "Espacio disponible: $espacioDisponible Mb."  
				echo "Espacio requerido: $DATASIZE Mb."
				echo "Cancele la instalacion o intentelo nuevamente."  
				echo
				#pido que el user vuelva a ingresar un tamano para el DATASIZE
				Pregunta_SiNo "Desea cancelar? (si) o elegir un nuevo espacio para el arribo de novedades en Mbytes(no) si-no"
				if [ "$?" == 1 ] 
				then
					exit 1
				fi
				echo "Vuelva a definir un espacio minimo libre para el arribo de novedades en Mbytes "
				Obtener_numero DATASIZE "Espacio minimo libre para el arribo de novedades en Mbytes (100):" "error" "100" 1
				DATASIZE=$(Verificar_tamano "$DATASIZE" $DATASIZE)
			done
			echo 		
			# solicito valor de ACEPDIR
			echo "Defina el directorio de grabacion de las Novedades aceptadas ($ACEPDIR):"
			Obtener_path ACEPDIR "Directorio de grabacion de las Novedades aceptadas ($ACEPDIR):" "$ACEPDIR"		
			echo
			# solicito valor de INFODIR
			echo "Defina el directorio de grabación de los informes de salida ($INFODIR):"
			Obtener_path INFODIR "Directorio de grabación de los informes de salida ($INFODIR):" "$INFODIR"
			echo
			# solicito valor de RECHDIR
			echo "Defina el directorio de grabacion de Archivos rechazados ($RECHDIR):"
			Obtener_path RECHDIR "Directorio de grabación de Archivos rechazados ($RECHDIR):" "$RECHDIR"
			echo			
			# solicito valor de LOGDIR
			echo "Defina el directorio de logs ($LOGDIR):"
			Obtener_path LOGDIR "Directorio de logs ($LOGDIR):" "$LOGDIR"
			echo
			# solicito valor de LOGEXT (EXTENSION)
			echo "Ingrese la extension para los archivos de log ($LOGEXT):"
			Obtener_valor LOGEXT "La extension para los archivos de log es:" "$LOGEXT" 
			echo 
			#verifico valor maximo para los archivos de log LOGSIZE
			echo "Defina el tamaño maximo para los archivos $LOGEXT en Kbytes ($LOGSIZE):"		
			Obtener_numero LOGSIZE "Tamaño maximo para los archivos $LOGEXT en Kbytes ($LOGSIZE):" "error" $LOGSIZE 1		
			clear
			# estructura de directorios resultante y valores de los parámetros configurados
			echo "TP SO7508 Primer Cuatrimestre 2014. Tema C Copyright © Grupo 01"
			Path_y_Archivos "Direct. de Configuracion: " "$CONFDIR" 1
			Path_y_Archivos "Directorio Ejecutables: " "$BINDIR" 1
			Path_y_Archivos "Directorio Maestros y Tablas:" "$MAEDIR" 1
			Path_y_Archivos "Directorio de Novedades:" "$NOVEDIR" 0
			Path_y_Archivos "Espacio mínimo libre para arribos:" "$DATASIZE Mb" 0
			Path_y_Archivos "Directiorio Novedades Aceptadas:" "$ACEPDIR" 0
			Path_y_Archivos "Directorio Informes de Salida:" "$INFODIR" 0
			Path_y_Archivos "Directorio Archivos Rechazados:" "$RECHDIR" 0
			echo "Directorio de Logs de Comandos: $LOGDIR /<comando>$LOGEXT"
			echo "Tamano maximo para los archivos de log del sistema:" "$LOGSIZE" "Kb"
			echo "Estado de la instalacion: LISTA"
			Pregunta_SiNo "Iniciando Instalación. Esta Ud. seguro? (Si-No)"
			instalar=$?			
			respuestaInstalacion="si"
			if [ $instalar -eq 0 ]
			then
				respuestaInstalacion="no"
			fi
			./datos/bin/Logging Installer "Iniciando Instalacion. Esta Ud. seguro? (Si-No): $respuestaInstalacion" INFO
		done
		Creacion_de_directorios 0
		Instalacion_archivos
		#creo archivo de conf
		touch "$CONFDIR/Installer.conf"

		Actualizacion_archivos_configuracion
		echo "INSTALACION CONCLUIDA"
		./datos/bin/Logging Installer "Intalacion CONCLUIDA" INFO 
	fi
	chmod 777 "$BINDIR"/Initializer
fi















